### ISSUE TITLE
Quarantine / App Translocation causes app to immediately crash

### ISSUE THREAD

**Issue by Ladygolem** [rgov/starter-pack#1]

**Comment by rgov** [comment]
Thanks for being the first tester 👍 

What system are you running on? I'm on macOS 10.13.5 on a 64-bit Mac.

Does it create a file called "stderr.txt"? If so, can you attach it?

Or could you right-click on the Starter Pack Launcher app, and click "Show Package Contents" and browse to Contents/MacOS. Find the file called "PyLNP" in this folder. Then open up Terminal and drag the PyLNP file to the Terminal window and hit return.  What output shows up?

**Comment by Ladygolem** [comment]
I'm on macOS 10.12.6 on a 64-bit Mac. I'm updating my system, will see if that affects things. 

Meanwhile: can't see any stderr.txt, where would it be located?

When dragging the file to terminal, I get this:

`ip-10-36-24-139:~ slimegirl$ /Users/slimegirl/Downloads/Mac\ Starter\ Pack/Starter\ Pack\ Launcher\ \(PyLNP\).app/Contents/MacOS/PyLNP `

**Comment by rgov** [comment]
The "stderr.txt" file appears alongside the Starter Pack Launcher application, but it may not be created.

Yeah that's what I expect the Terminal to show, then hit "return" to actually run the command and some more output should show up.

**Comment by Ladygolem** [comment]
Yeah, I forgot to press Return, haha. Silly mistake. Seems to be running now though at least.

**Comment by rgov** [comment]
So it runs from within Terminal but does *not* run when you double click the .app?

**Comment by Ladygolem** [comment]
Yup! Also, got a stderr.txt file now: 
[stderr.txt](https://github.com/rgov/starter-pack/files/2155414/stderr.txt)
Sorry if I'm being unhelpful, I'm not a programmer of any sort. Let me know if there's anything else I can do.

**Comment by rgov** [comment]
No worry at all, I figured out how to reproduce the issue. If you find any other problems, please submit them in a [new issue](https://github.com/rgov/starter-pack/issues/new).

I believe if you copy the Mac Starter Pack folder out of your Downloads folder, it will work with a double click.

**Comment by rgov** [comment]
Yes, it is App Translocation:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```

**Comment by Ladygolem** [comment]
Copied folder to desktop, still experiencing issue.

**Comment by rgov** [comment]
Did you copy just the .app ("Starter Pack Launcher") or the whole outer folder, which includes "Dwarf Fortress 0.44.10" etc.?

**Comment by Ladygolem** [comment]
Whole folder. Should I have copied the app itself?

**Comment by rgov** [comment]
No, I think you did it right, but I'd expect that to have fixed it. How did you copy it? Just drag and drop?

**Comment by Ladygolem** [comment]
Tried that, didn't work, went back and Ctrl+C Ctrl+V'd, didn't work either.

**Comment by rgov** [comment]
In the latest release, there should be a warning if this security feature is active. Please give it a try. https://github.com/rgov/starter-pack/releases/tag/v0.44.12-r02-mac-alpha
