### ISSUE TITLE
Terminal command terminated my game play

### ISSUE THREAD

**Issue by Flint-Firefudge** [rgov/starter-pack#10]
I'll try to make this short.  I don't know what info is important so I'll just give the brief rundown.   I installed this on an older iMac utilizing OSx 10.6.8.  Was using the LAZY MAC PACK but heard the MAC STARTER PACK was more up to date so I uninstalled the previous and installed the latter.  I entered the Terminal line, replacing the directory as requested, and when hitting "play Dwarf Fortress, Terminal pops up and dumps this on me:

Last login: Wed Jan 23 15:41:48 on console
/Users/bmitch10/Desktop/Mac\ Starter\ Pack\ 2/Dwarf\ Fortress\ 0.44.12/dfhack ; exit;
James-Mitchells-iMac:~ bmitch10$ /Users/bmitch10/Desktop/Mac\ Starter\ Pack\ 2/Dwarf\ Fortress\ 0.44.12/dfhack ; exit;
dyld: Library not loaded: /opt/local/lib/libz.1.dylib
  Referenced from: /Users/bmitch10/Desktop/Mac Starter Pack 2/Dwarf Fortress 0.44.12/hack/libdfhack.1.0.0.dylib
  Reason: image not found
/Users/bmitch10/Desktop/Mac Starter Pack 2/Dwarf Fortress 0.44.12/dfhack: line 15:   809 Trace/BPT trap          DYLD_INSERT_LIBRARIES=./hack/libdfhack.dylib ./dwarfort.exe "$@"

logout

[Process completed]

I obviously have no idea what I'm looking at.  Would love to get it cleared up so I can actually run the game again as the Lazy Mac Pack will also not run and gives me the Terminal dump.  Thanks for the time.

**Comment by rgov** [comment]
I think it's unlikely that I will be able to have the time to get this working on 10.6.8—Snow Leopard is a decade old. Can you reproduce on a newer version?

It's saying that the file `/opt/local/lib/libz.1.dylib` is not found. You should file a bug against dfhack that says they should not be linking against dependencies on /opt/.

In the meantime, you can try to use Homebrew or MacPorts or something to install the package "zlib" as long as it ends up in that directory... Sorry, I don't know have specific instructions.
