### ISSUE TITLE
Update Time!

### ISSUE THREAD

**Issue by aljfdbgaliudhfbn** [rgov/starter-pack#4]
The Starter Pack has updated to 0.44.12-r01!

"0.44.12-r01
 - updated Dwarf Fortress
 - updated DFHack to 0.44.12-r1
 - updated TwbT to v6.53
 - updated Dwarf Therapist to v40.1.2
 - updated Legends Viewer to 1.19.09
 - updated graphics: Ironhand, Obsidian, Spacefox, Phoebus

SHA256:  1b5d95b2310fc1311a6a7b12a7b08c2daadd8b01c8b0892d53303a230ede3f6d"

http://www.bay12forums.com/smf/index.php?topic=126076.msg7807930#msg7807930

Thanks for your work!

**Comment by rgov** [comment]
0.44.12-r02 was subsequently released.

PeridexisErrant did not make any changes to the starter pack repo, so either it required no changes, or they made changes in private and did not release them. I hope it's the former.

**Comment by aljfdbgaliudhfbn** [comment]
Sorry for the dumb question- If the 0.44.12-r02 required no changes for your pack, how do I go about installing updates?

**Comment by rgov** [comment]
You can clone this repo and run the `main.py` script which will download all of the parts. I'm working on a release. I want to include a new PyLNP with some improvements for macOS, and solve the security issues.

**Comment by rgov** [comment]
Michael of the PyNLP project says a new release will be made within a week, and I'll release a new build of the starter pack when it is available.

**Comment by rgov** [comment]
https://github.com/rgov/starter-pack/releases/tag/v0.44.12-r02-mac-alpha

**Comment by aljfdbgaliudhfbn** [comment]
Thanks Man!
