### ISSUE TITLE
Terminal command listed on main page doesn't work

### ISSUE THREAD

**Issue by Ladygolem** [rgov/starter-pack#5]
Returns this: `xattr: No such file: /Users/slimegirl/Downloads/Mac Starter Pack/Dwarf Fortress 0.44.12/libs/SDL_image.framework/Frameworks`

Upon inspection, where that file should be there's an alias that leads to a nonexistent destination.

[Screenshot 1](https://puu.sh/B0j0h/d24bb6d08b.png)
[Screenshot 2](https://puu.sh/B0j0C/0a98fe4bae.png)

Apologies if I'm missing something obvious here - again, I have no tech experience beyond playing the game itself. Hope this helps.

**Comment by Ladygolem** [comment]
On the other hand: right-click > Open works just fine, so maybe that's not an issue?

**Comment by rgov** [comment]
Yes you are correct this symlink is a troublemaker. I’ll remove it and some other junk in the next release, and report it to the DF team.
