### ISSUE TITLE
Need to include the updated SDL TTF library for 10.8+

### ISSUE THREAD

**Issue by jobywalker** [rgov/starter-pack#8]
The bundled SDL_ttf framework includes links to freetype which is not included with macOS since 10.8. Updating to [2.0.11](https://www.libsdl.org/projects/SDL_ttf/release/SDL_ttf-2.0.11.dmg) fixes this.

dyld: Library not loaded: @rpath/freetype.framework/Versions/2.6.3/freetype
  Referenced from: /Volumes/Imperium/starter-pack/dist/Dwarf Fortress 0.44.12/libs/SDL_ttf.framework/Versions/A/SDL_ttf
  Reason: image not found

**Comment by rgov** [comment]
Please feel free to submit a pull request. I didn't see any dyld errors on my end but if updating works, that's fine.

**Comment by jobywalker** [comment]
Hmm. l notes on the [related bug](http://www.bay12games.com/dwarves/mantisbt/view.php?id=7389), that it was fixed in 43.05, but I've regularly seen this issue. I had thought you added the library yourself because I didn't run into that issue with the release you put out. I'll check what I'm doing some more to see what the issue is.

**Comment by jobywalker** [comment]
I think this may be due to the packager. I can successfully run a clean download. I'll do some more testing to see what the issue might be.

**Comment by jobywalker** [comment]
Closing this -- found the issue, I was building on a case sensitive filesystem. Moving to my main partition solved the issue.
